<section>
    <article>
        <header>
            <h2>One Day...Revisited</h2>
        </header>
        <div>
            <p>I forgot!</p>
            <p>I already am writing a book!</p>
        </div>
        <footer>
            <address>By Pádraic</address>
        </footer>
    </article>

    <article>
        <header>
            <h2>One Day...</h2>
        </header>
        <div>
            <p>I will write a book</p>
        </div>
        <footer>
            <address>By Pádraic</address>
        </footer>
    </article>
</section>
