<article>
    <header>
        <h2>One Day...Revisited</h2>
        <p>Posted on <time datetime="2009-09-07">Tuesday, 08 September 2009</time></p>
    </header>
    <div>
        <p>I forgot!</p>
        <p>I already am writing a book!</p>
    </div>
    <footer>
        <address>By Pádraic</address>
    </footer>
</article>

<article>
    <header>
        <h2>One Day...</h2>
        <p>Posted on <time datetime="2009-09-07">Monday, 07 September 2009</time></p>
    </header>
    <div>
        <p>I will write a book</p>
    </div>
    <footer>
        <address>By Pádraic</address>
    </footer>
</article>
